cut-body-after = "---"
delete-merged-branches = true

status = [
  "Torture (macos-latest, stable)",
  "Torture (macos-latest, beta)",
  "Torture (ubuntu-latest, stable)",
  "Torture (ubuntu-latest, beta)",
  "Torture (windows-latest, stable)",
  "Torture (windows-latest, beta)",
  "Test (macos-latest, stable)",
  "Test (macos-latest, beta)",
  "Test (ubuntu-latest, stable)",
  "Test (ubuntu-latest, beta)",
  "Test (windows-latest, stable)",
  "Test (windows-latest, beta)"
]
