[package]
name = "elm-torture"
version = "0.1.0"
authors = ["Harry Sarson <harry.sarson@hotmail.co.uk>"]
edition = "2018"

[dependencies]
clap = "2"
which = "3.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.7"
rust-embed = "5.5.1"
same-file = "1.0.6"
tempfile = "3.1.0"
indented = "0.1.0"
colored = "1.9"
replace_with = "0.1.5"
humantime-serde = "1.0.0"
pathdiff = "0.2.0"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.5"
humantime = "2.0.0"
