name: Rust

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Install elm
        run: npm i -g elm@0.19.0-no-deps
      - name: Basic torture run
        run: cargo run -- --suites suite --config ./ci/config/basic.json
      - name: Debug torture run
        run: cargo run -- --suites suite --config ./ci/config/debug.json
      - name: Optimized torture run
        run: cargo run -- --suites suite --config ./ci/config/optimise.json
