name: Rust

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --verbose
      - name: Allow npm global installs
        run: sudo chown -R $USER /usr/local/lib/node_modules && sudo chown $USER /usr/local/bin
        if: runner.os != 'Windows'
      - name: Install elm
        run: npm i -g elm@0.19.0-no-deps
      - name: Basic torture run
        run: cargo run -- --suites suite --config ./ci/config/basic.json
      - name: Debug torture run
        run: cargo run -- --suites suite --config ./ci/config/debug.json
      - name: Optimized torture run
        run: cargo run -- --suites suite --config ./ci/config/optimize.json
